branches:
    only:
      - master
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      
os: linux
dist: trusty
language: bash
sudo: false
cache:
  directories:
    - ~/arduino_ide
  #  - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="WiFi Connect"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

matrix:

  include:

    - env:

      - BUILD_TYPE=build_esp8266

    - env:

      - BUILD_TYPE=build_esp32

before_install:


install:


script:
   - $TRAVIS_BUILD_DIR/travis/common.sh

# Generate and deploy documentation
after_success:
  # - source <(curl -SLs  https://raw.githubusercontent.com/smurf0969/travis-ci-arduino/master/library_check.sh)
  # - source <(curl -SLs  https://raw.githubusercontent.com/smurf0969/travis-ci-arduino/skip-doxygen-warnings/doxy_gen_and_deploy.sh)
