branches:
    only:
      - master
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
  submodules: false
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.7"
     - PRETTYNAME="WiFi Connect"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/smurf0969/travis-ci-arduino/master/install.sh)

install:
   - mkdir -p $HOME/arduino_ide/libraries
   - git clone --branch=Allow-overriding-default-font https://github.com/smurf0969/esp8266-oled-ssd1306 $HOME/arduino_ide/libraries
   - git clone https://github.com/bblanchon/ArduinoJson $HOME/arduino_ide/libraries

script:
   - build_main_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/smurf0969/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs  https://raw.githubusercontent.com/smurf0969/travis-ci-arduino/skip-doxygen-warnings/doxy_gen_and_deploy.sh)
